spring:
  application:
    name: talentai
  profiles:
    active: qa
  config:
    import: "optional:configserver:http://localhost:8071"
  datasource:
    url: jdbc:mysql://localhost:3306/talent_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


