services:
  accounts:
    image: "nayan011/talentaius"
    container_name: talentaius-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - talentai
networks:
  talentai:
    driver: "bridge"